baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[[menus.main]]
name = 'Post'
pageRef = '/'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1