baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Yorkin.io'
theme = 'Yoo'
summaryLength = 2

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1